AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for imageprocessing-demo
Globals:
  Function:
    Timeout: 600
    MemorySize: 1024

Resources:
  ImageResizer:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - S3FullAccessPolicy:
            BucketName: 'imageprocessing-demo'
